[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["AI", "Agent", "OpenAI", "Model", "Provider"]
license = ["Apache-2.0"]
name = "ai.openai"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.openai"
version = "1.0.0"

[platform.java21]
graalvmCompatible = true
