[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["Agent", "Model", "Provider", "Vendor/OpenAI", "Area/AI", "Type/Connector"]
license = ["Apache-2.0"]
icon="icon.png"
name = "ai.openai"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.openai"
version = "1.3.1"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ai.openai-native"
version = "1.3.1"
path = "../native/build/libs/ai.openai-native-1.3.1.jar"
