[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["AI", "Agent", "OpenAI", "Model", "Provider"]
license = ["Apache-2.0"]
icon="icon.png"
name = "ai.openai"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.openai"
version = "1.2.3"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ai.openai-native"
version = "1.2.3"
path = "../native/build/libs/ai.openai-native-1.2.3-SNAPSHOT.jar"

[[dependency]]
org="ballerina"
name="ai"
version="1.6.0"
repository="local"